### PR TITLE
KPI chart

### PR DESCRIPTION
**Pull request by asprincean**
image

### CODE REVIEW

**Review by michaelcairney — APPROVED** [review]
Nice! In the image you provided the white box seems to be larger than the rest, is that supposed to be the case?

**Comment by asprincean** [comment]
> Nice! In the image you provided the white box seems to be larger than the rest, is that supposed to be the case?

Thanks, the white box is for when an user clicks on a diamond displayed on timeline

**Review by rellisbrown — APPROVED** [review]
Looks good! I just made another commit where I added in a filter /fade effect for the edges of the slider

**Comment by asprincean** [comment]
> Looks good! I just made another commit where I added in a filter /fade effect for the edges of the slider

Thank you!

**Pull request merged**
